// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK8RSaY0YG5crah4N99cJK2qi3L5dLnZ0',
    appId: '1:412384698396:web:1d760b50ccfebbd9d1ffd9',
    messagingSenderId: '412384698396',
    projectId: 'rezerv---hotel-booking-app',
    authDomain: 'rezerv---hotel-booking-app.firebaseapp.com',
    storageBucket: 'rezerv---hotel-booking-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArR4T6QeT02zc0mqlIqavbuCEwiTG2LU8',
    appId: '1:412384698396:android:88ed108e956012a4d1ffd9',
    messagingSenderId: '412384698396',
    projectId: 'rezerv---hotel-booking-app',
    storageBucket: 'rezerv---hotel-booking-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPjEYT2GDi4e8_Jt1k7xQm7izAQtfyu44',
    appId: '1:412384698396:ios:b5b71b933a7ab44cd1ffd9',
    messagingSenderId: '412384698396',
    projectId: 'rezerv---hotel-booking-app',
    storageBucket: 'rezerv---hotel-booking-app.appspot.com',
    iosBundleId: 'com.example.rezerv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPjEYT2GDi4e8_Jt1k7xQm7izAQtfyu44',
    appId: '1:412384698396:ios:b5b71b933a7ab44cd1ffd9',
    messagingSenderId: '412384698396',
    projectId: 'rezerv---hotel-booking-app',
    storageBucket: 'rezerv---hotel-booking-app.appspot.com',
    iosBundleId: 'com.example.rezerv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAK8RSaY0YG5crah4N99cJK2qi3L5dLnZ0',
    appId: '1:412384698396:web:84c1795448e4782fd1ffd9',
    messagingSenderId: '412384698396',
    projectId: 'rezerv---hotel-booking-app',
    authDomain: 'rezerv---hotel-booking-app.firebaseapp.com',
    storageBucket: 'rezerv---hotel-booking-app.appspot.com',
  );
}
